
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: job_hash
          AttributeType: S
        - AttributeName: share_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: job_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: share
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: share_id
              KeyType: RANGE
        - IndexName: job_hash
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: job_hash
              KeyType: HASH
      Tags:
        - Key: project
          Value: seed-find

  TableNameParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /seed-job-ddb/table-name
      Type: String
      Value: !Ref DynamoDBTable
      Description: The name of the DynamoDB table
      Tags:
        project: seed-find

  TableArnParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /seed-job-ddb/table-arn
      Type: String
      Value: !GetAtt DynamoDBTable.Arn
      Description: The ARN of the DynamoDB table
      Tags:
        project: seed-find

Outputs:
  TableArn:
    Value: !GetAtt DynamoDBTable.Arn
  TableName:
    Value: !Ref DynamoDBTable