export const schema = {
  type: "object",
  properties: {
    legacy_rng: { type: "boolean" },
    start_seed: { type: "integer" },
    end_seed: { type: "integer" },
    weather: {
      type: "array",
      items: {
        type: "object",
        properties: {
          weather: { $ref: "#/definitions/weather" },
          day: { type: "integer" },
        },
        required: ["weather", "day"],
      },
    },
    night_event: {
      type: "array",
      items: {
        type: "object",
        properties: {
          event: { $ref: "#/definitions/night_event" },
          day: { type: "integer" },
        },
        required: ["event", "day"],
      },
    },
    item_quest: {
      type: "array",
      items: {
        type: "object",
        properties: {
          day: { type: "integer" },
          person: { $ref: "#/definitions/villager" },
          id: { type: "string" },
          people_known: {
            type: "array",
            items: { $ref: "#/definitions/villager" },
          },
          has_furnace: { type: "boolean" },
          has_desert: { type: "boolean" },
          mine_level: { type: "integer" },
          has_socialize_quest: { type: "boolean" },
          cookie_recipes_known: { type: "integer" },
        },
        required: ["day", "person"],
      },
    },
  },
  required: [
    "legacy_rng",
    "start_seed",
    "end_seed",
    "weather",
    "night_event",
    "item_quest",
  ],
  additionalProperties: false,
  definitions: {
    villager: {
      enum: [
        "Abigail",
        "Alex",
        "Caroline",
        "Clint",
        "Demetrius",
        "Dwarf",
        "Elliott",
        "Emily",
        "Evelyn",
        "George",
        "Gus",
        "Haley",
        "Harvey",
        "Jas",
        "Jodi",
        "Kent",
        "Krobus",
        "Leah",
        "Leo",
        "Lewis",
        "Linus",
        "Marnie",
        "Maru",
        "Pam",
        "Penny",
        "Pierre",
        "Robin",
        "Sam",
        "Sandy",
        "Sebastian",
        "Shane",
        "Vincent",
        "Willy",
        "Wizard",
      ],
    },
    weather: { enum: ["Sunny", "Rain", "Storm", "Snow", "GreenRain"] },
    night_event: {
      enum: [
        "None",
        "Fairy",
        "Witch",
        "Meteor",
        "StoneOwl",
        "StrangeCapsule",
        "WindStorm",
      ],
    },
  },
};
