name: Deploying APP

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT  

jobs:
  deploy-app:
    name: Deploy Web Application
    runs-on: ubuntu-latest
    env:
      working-directory: app