name: Deploying Web App

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT  

jobs:
  deploy-app:
    name: Deploy Web Application
    runs-on: ubuntu-latest
    env:
      working-directory: app
  
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: github-action-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy Bucket and CDN
        id: deploy-bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: seed-web-app
          template: ${{ env.working-directory }}/cfn/template.yml
          no-fail-on-empty-changeset: "1"

      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'