name: deploy cfn resources

on:
  push:
    branches: ["main"]
    paths:
      - "cfn/**"

permissions:
  id-token: write # This is required for requesting the JWT  

jobs:
  deploy:
    name: Assume AWS role
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: github-action-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: deploy database
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
            name: seed-job-ddb
            template: cfn/dynamodb.yaml
