name: Deploying application

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - "api/**"
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT  

jobs:
  deploy-api:
    name: Deploy Api
    runs-on: ubuntu-latest
    env:
      working-directory: api
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: github-action-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: deploy ecr
        id: deploy-ecr
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
            name: seed-api-ecr
            template: ${{ env.working-directory }}/cfn/ecr.yml
            no-fail-on-empty-changeset: "1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: ${{ env.working-directory }}
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ steps.deploy-ecr.outputs.RepositoryName }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy api
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
            name: seed-api-lambda
            template: ${{ env.working-directory }}/cfn/lambda-api.yml
            capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
            no-fail-on-empty-changeset: "1"
            parameter-overrides: >-
              ImageTag=${{ github.sha }},
              Repository=${{ steps.deploy-ecr.outputs.RepositoryName }}